# General Coding

In [1]:
import numpy as np

In [2]:
import itertools

In [42]:
x=int(input())
y=int(input())
z=int(input())
n=int(input())

1
1
1
2


In [29]:
xyzn = list(itertools.permutations([int(x),int(y),int(z),int(n)],3))
xyzn

[(0, 0, 1),
 (0, 0, 1),
 (0, 1, 0),
 (0, 1, 1),
 (0, 1, 0),
 (0, 1, 1),
 (0, 0, 1),
 (0, 0, 1),
 (0, 1, 0),
 (0, 1, 1),
 (0, 1, 0),
 (0, 1, 1),
 (1, 0, 0),
 (1, 0, 1),
 (1, 0, 0),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 0),
 (1, 0, 0),
 (1, 0, 1),
 (1, 0, 0),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 0)]

In [30]:
output=[]
for i, tup in enumerate(xyzn):
    if sum(tup)!=n:
#         print(sum(tup))
        output.append(tup)

output

[(0, 1, 1),
 (0, 1, 1),
 (0, 1, 1),
 (0, 1, 1),
 (1, 0, 1),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 0),
 (1, 0, 1),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 0)]

In [31]:
print(len(xyzn))
print(len(output))

24
12


In [27]:
n

'1'

In [47]:
i=list(range(x+1))
j=list(range(y+1))
k=list(range(z+1))

In [55]:
list(itertools.permutations((i,j,k),3))

[([0, 1], [0, 1], [0, 1]),
 ([0, 1], [0, 1], [0, 1]),
 ([0, 1], [0, 1], [0, 1]),
 ([0, 1], [0, 1], [0, 1]),
 ([0, 1], [0, 1], [0, 1]),
 ([0, 1], [0, 1], [0, 1])]

In [49]:
i

[0, 1]

In [59]:
permutations=[]
for alli in i:
    for allj in j:
        for allk in k:
            permutations.append([alli,allj,allk])
            
permutations

[[0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 1]]

In [60]:
output2 = []
for p in permutations:
    if sum(p)!=n:
        output2.append(p)

In [61]:
output2

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

In [58]:
i=range(x+1)
j=range(y+1)
k=range(z+1)

In [62]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())
i=range(x+1)
j=range(y+1)
k=range(z+1) 
permutations=[]
for alli in i:
    for allj in j:
        for allk in k:
            permutations.append([alli,allj,allk])       
output=[]
for p in permutations:
    if sum(p)!=n:
        output.append(p)
output

1
1
1
2


[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

In [63]:
def fun(x,y,z,n):
    i=range(x+1)
    j=range(y+1)
    k=range(z+1) 
    permutations=[]
    for alli in i:
        for allj in j:
            for allk in k:
                permutations.append([alli,allj,allk])       
    output=[]
    for p in permutations:
        if sum(p)!=n:
            output.append(p)
    return output

fun(x,y,z,n)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

In [75]:
n = int(input())
arr = map(int, input().split())

5
5 4 3 2 1


In [76]:
arrlist = list(arr)
arrlist

[5, 4, 3, 2, 1]

In [78]:
arrlist.sort()

In [79]:
len(arrlist)

5

In [80]:
arrlist

[1, 2, 3, 4, 5]

In [82]:
max(arrlist)

5

In [83]:
finallist=[i for i in arrlist if i!=max(arrlist)]
finallist

[1, 2, 3, 4]

In [84]:
print(max(finallist))

4


In [101]:
name_=[]
score_=[]
for _ in range(int(input())):
    name = input()
    score = float(input())
    name_.append(name)
    score_.append(score)
    
list_main = [[name_[i],score_[i]] for i in range(len(name_))]

4
neha
28
swets
40
dad
30
mom
30


In [102]:
list_main = [[name_[i],score_[i]] for i in range(len(name_))]
list_main

[['neha', 28.0], ['swets', 40.0], ['dad', 30.0], ['mom', 30.0]]

In [103]:
name_

['neha', 'swets', 'dad', 'mom']

In [104]:
score_

[28.0, 40.0, 30.0, 30.0]

In [105]:
scorefin = [i for i in score_ if i!=min(score_)]
seclow = min(scorefin)

In [106]:
stud = [n[0] for n in [list_main[k] for k in range(len(list_main))] if n[1]==seclow]
stud

['dad', 'mom']

In [107]:
seclow

30.0

In [117]:
for i in range(len(stud)):
    print(stud[i])

dad
mom


In [116]:
stud

['dad', 'mom']

In [111]:
len(stud)

2

# NLP

## Corpus Statistics - Lab

In [1]:
import nltk
from nltk.corpus import gutenberg, stopwords
from nltk.collocations import *
from nltk import FreqDist, word_tokenize
import string
import re

In [2]:
nltk.download('gutenberg')

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\19035\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


True

In [3]:
file_ids = gutenberg.fileids()
file_ids

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [4]:
macbeth_text = gutenberg.raw('shakespeare-macbeth.txt')
macbeth_text[:1000]

"[The Tragedie of Macbeth by William Shakespeare 1603]\n\n\nActus Primus. Scoena Prima.\n\nThunder and Lightning. Enter three Witches.\n\n  1. When shall we three meet againe?\nIn Thunder, Lightning, or in Raine?\n  2. When the Hurley-burley's done,\nWhen the Battaile's lost, and wonne\n\n   3. That will be ere the set of Sunne\n\n   1. Where the place?\n  2. Vpon the Heath\n\n   3. There to meet with Macbeth\n\n   1. I come, Gray-Malkin\n\n   All. Padock calls anon: faire is foule, and foule is faire,\nHouer through the fogge and filthie ayre.\n\nExeunt.\n\n\nScena Secunda.\n\nAlarum within. Enter King Malcome, Donalbaine, Lenox, with\nattendants,\nmeeting a bleeding Captaine.\n\n  King. What bloody man is that? he can report,\nAs seemeth by his plight, of the Reuolt\nThe newest state\n\n   Mal. This is the Serieant,\nWho like a good and hardie Souldier fought\n'Gainst my Captiuitie: Haile braue friend;\nSay to the King, the knowledge of the Broyle,\nAs thou didst leaue it\n\n   Cap. 

In [5]:
print(macbeth_text[:1000])

[The Tragedie of Macbeth by William Shakespeare 1603]


Actus Primus. Scoena Prima.

Thunder and Lightning. Enter three Witches.

  1. When shall we three meet againe?
In Thunder, Lightning, or in Raine?
  2. When the Hurley-burley's done,
When the Battaile's lost, and wonne

   3. That will be ere the set of Sunne

   1. Where the place?
  2. Vpon the Heath

   3. There to meet with Macbeth

   1. I come, Gray-Malkin

   All. Padock calls anon: faire is foule, and foule is faire,
Houer through the fogge and filthie ayre.

Exeunt.


Scena Secunda.

Alarum within. Enter King Malcome, Donalbaine, Lenox, with
attendants,
meeting a bleeding Captaine.

  King. What bloody man is that? he can report,
As seemeth by his plight, of the Reuolt
The newest state

   Mal. This is the Serieant,
Who like a good and hardie Souldier fought
'Gainst my Captiuitie: Haile braue friend;
Say to the King, the knowledge of the Broyle,
As thou didst leaue it

   Cap. Doubtfull it stood,
As two spent Swimmers, t

In [6]:
pattern = "([a-zA-Z]+(?:'[a-z]+)?)"
macbeth_tokens_raw = nltk.regexp_tokenize(macbeth_text,pattern)
macbeth_tokens_raw

['The',
 'Tragedie',
 'of',
 'Macbeth',
 'by',
 'William',
 'Shakespeare',
 'Actus',
 'Primus',
 'Scoena',
 'Prima',
 'Thunder',
 'and',
 'Lightning',
 'Enter',
 'three',
 'Witches',
 'When',
 'shall',
 'we',
 'three',
 'meet',
 'againe',
 'In',
 'Thunder',
 'Lightning',
 'or',
 'in',
 'Raine',
 'When',
 'the',
 'Hurley',
 "burley's",
 'done',
 'When',
 'the',
 "Battaile's",
 'lost',
 'and',
 'wonne',
 'That',
 'will',
 'be',
 'ere',
 'the',
 'set',
 'of',
 'Sunne',
 'Where',
 'the',
 'place',
 'Vpon',
 'the',
 'Heath',
 'There',
 'to',
 'meet',
 'with',
 'Macbeth',
 'I',
 'come',
 'Gray',
 'Malkin',
 'All',
 'Padock',
 'calls',
 'anon',
 'faire',
 'is',
 'foule',
 'and',
 'foule',
 'is',
 'faire',
 'Houer',
 'through',
 'the',
 'fogge',
 'and',
 'filthie',
 'ayre',
 'Exeunt',
 'Scena',
 'Secunda',
 'Alarum',
 'within',
 'Enter',
 'King',
 'Malcome',
 'Donalbaine',
 'Lenox',
 'with',
 'attendants',
 'meeting',
 'a',
 'bleeding',
 'Captaine',
 'King',
 'What',
 'bloody',
 'man',
 'is',


In [7]:
macbeth_tokens = [x.lower() for x in macbeth_tokens_raw]
macbeth_tokens

['the',
 'tragedie',
 'of',
 'macbeth',
 'by',
 'william',
 'shakespeare',
 'actus',
 'primus',
 'scoena',
 'prima',
 'thunder',
 'and',
 'lightning',
 'enter',
 'three',
 'witches',
 'when',
 'shall',
 'we',
 'three',
 'meet',
 'againe',
 'in',
 'thunder',
 'lightning',
 'or',
 'in',
 'raine',
 'when',
 'the',
 'hurley',
 "burley's",
 'done',
 'when',
 'the',
 "battaile's",
 'lost',
 'and',
 'wonne',
 'that',
 'will',
 'be',
 'ere',
 'the',
 'set',
 'of',
 'sunne',
 'where',
 'the',
 'place',
 'vpon',
 'the',
 'heath',
 'there',
 'to',
 'meet',
 'with',
 'macbeth',
 'i',
 'come',
 'gray',
 'malkin',
 'all',
 'padock',
 'calls',
 'anon',
 'faire',
 'is',
 'foule',
 'and',
 'foule',
 'is',
 'faire',
 'houer',
 'through',
 'the',
 'fogge',
 'and',
 'filthie',
 'ayre',
 'exeunt',
 'scena',
 'secunda',
 'alarum',
 'within',
 'enter',
 'king',
 'malcome',
 'donalbaine',
 'lenox',
 'with',
 'attendants',
 'meeting',
 'a',
 'bleeding',
 'captaine',
 'king',
 'what',
 'bloody',
 'man',
 'is',


In [8]:
macbeth_freqdist = FreqDist(macbeth_tokens)
macbeth_freqdist.most_common(50)

[('the', 649),
 ('and', 545),
 ('to', 383),
 ('of', 338),
 ('i', 331),
 ('a', 241),
 ('that', 227),
 ('my', 203),
 ('you', 203),
 ('in', 199),
 ('is', 180),
 ('not', 165),
 ('it', 161),
 ('with', 153),
 ('his', 146),
 ('be', 137),
 ('macb', 137),
 ('your', 126),
 ('our', 123),
 ('haue', 122),
 ('but', 120),
 ('me', 113),
 ('he', 110),
 ('for', 109),
 ('what', 106),
 ('this', 104),
 ('all', 99),
 ('so', 96),
 ('him', 90),
 ('as', 89),
 ('thou', 87),
 ('we', 83),
 ('enter', 81),
 ('which', 80),
 ('are', 73),
 ('will', 72),
 ('they', 70),
 ('shall', 68),
 ('no', 67),
 ('then', 63),
 ('macbeth', 62),
 ('their', 62),
 ('thee', 61),
 ('vpon', 58),
 ('on', 58),
 ('macd', 58),
 ('from', 57),
 ('yet', 57),
 ('thy', 56),
 ('vs', 55)]

In [9]:
list(string.punctuation)

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [10]:
stopwords_list = stopwords.words('english')
stopwords_list += list(string.punctuation)
stopwords_list += ['0','1','2','3','4','5','6','7','8','9']

macbeth_words_stopped = [x for x in macbeth_tokens if x not in stopwords_list]
macbeth_words_stopped

['tragedie',
 'macbeth',
 'william',
 'shakespeare',
 'actus',
 'primus',
 'scoena',
 'prima',
 'thunder',
 'lightning',
 'enter',
 'three',
 'witches',
 'shall',
 'three',
 'meet',
 'againe',
 'thunder',
 'lightning',
 'raine',
 'hurley',
 "burley's",
 'done',
 "battaile's",
 'lost',
 'wonne',
 'ere',
 'set',
 'sunne',
 'place',
 'vpon',
 'heath',
 'meet',
 'macbeth',
 'come',
 'gray',
 'malkin',
 'padock',
 'calls',
 'anon',
 'faire',
 'foule',
 'foule',
 'faire',
 'houer',
 'fogge',
 'filthie',
 'ayre',
 'exeunt',
 'scena',
 'secunda',
 'alarum',
 'within',
 'enter',
 'king',
 'malcome',
 'donalbaine',
 'lenox',
 'attendants',
 'meeting',
 'bleeding',
 'captaine',
 'king',
 'bloody',
 'man',
 'report',
 'seemeth',
 'plight',
 'reuolt',
 'newest',
 'state',
 'mal',
 'serieant',
 'like',
 'good',
 'hardie',
 'souldier',
 'fought',
 'gainst',
 'captiuitie',
 'haile',
 'braue',
 'friend',
 'say',
 'king',
 'knowledge',
 'broyle',
 'thou',
 'didst',
 'leaue',
 'cap',
 'doubtfull',
 'stoo

In [11]:
macbeth_stopped_freqdist = FreqDist(macbeth_words_stopped)
macbeth_stopped_freqdist.most_common(50)

[('macb', 137),
 ('haue', 122),
 ('thou', 87),
 ('enter', 81),
 ('shall', 68),
 ('macbeth', 62),
 ('thee', 61),
 ('vpon', 58),
 ('macd', 58),
 ('yet', 57),
 ('thy', 56),
 ('vs', 55),
 ('come', 54),
 ('king', 54),
 ('hath', 52),
 ('good', 49),
 ('rosse', 49),
 ('lady', 48),
 ('would', 47),
 ('time', 46),
 ('like', 43),
 ('say', 39),
 ('doe', 38),
 ('lord', 38),
 ('make', 38),
 ('tis', 37),
 ('must', 36),
 ('done', 35),
 ('selfe', 35),
 ('ile', 35),
 ('feare', 35),
 ('let', 35),
 ('man', 34),
 ('wife', 34),
 ('night', 34),
 ('banquo', 34),
 ('well', 33),
 ('know', 33),
 ('one', 32),
 ('great', 31),
 ('see', 31),
 ('may', 31),
 ('exeunt', 30),
 ('speake', 29),
 ('sir', 29),
 ('lenox', 28),
 ('mine', 26),
 ('vp', 26),
 ('th', 26),
 ('mal', 25)]

In [12]:
len(macbeth_stopped_freqdist)

3441

In [13]:
macbeth_stopped_freqdist.most_common(50)

[('macb', 137),
 ('haue', 122),
 ('thou', 87),
 ('enter', 81),
 ('shall', 68),
 ('macbeth', 62),
 ('thee', 61),
 ('vpon', 58),
 ('macd', 58),
 ('yet', 57),
 ('thy', 56),
 ('vs', 55),
 ('come', 54),
 ('king', 54),
 ('hath', 52),
 ('good', 49),
 ('rosse', 49),
 ('lady', 48),
 ('would', 47),
 ('time', 46),
 ('like', 43),
 ('say', 39),
 ('doe', 38),
 ('lord', 38),
 ('make', 38),
 ('tis', 37),
 ('must', 36),
 ('done', 35),
 ('selfe', 35),
 ('ile', 35),
 ('feare', 35),
 ('let', 35),
 ('man', 34),
 ('wife', 34),
 ('night', 34),
 ('banquo', 34),
 ('well', 33),
 ('know', 33),
 ('one', 32),
 ('great', 31),
 ('see', 31),
 ('may', 31),
 ('exeunt', 30),
 ('speake', 29),
 ('sir', 29),
 ('lenox', 28),
 ('mine', 26),
 ('vp', 26),
 ('th', 26),
 ('mal', 25)]

In [14]:
total_word_count = len(macbeth_stopped_freqdist)
macbeth_top_50 = macbeth_stopped_freqdist.most_common(50)
print('Word\t\t\tNormalized Frequency')
for word in macbeth_top_50:
    normalized_frequency = word[1]/total_word_count
    print('{} \t\t\t {:.4}'.format(word[0], normalized_frequency))

Word			Normalized Frequency
macb 			 0.03981
haue 			 0.03545
thou 			 0.02528
enter 			 0.02354
shall 			 0.01976
macbeth 			 0.01802
thee 			 0.01773
vpon 			 0.01686
macd 			 0.01686
yet 			 0.01656
thy 			 0.01627
vs 			 0.01598
come 			 0.01569
king 			 0.01569
hath 			 0.01511
good 			 0.01424
rosse 			 0.01424
lady 			 0.01395
would 			 0.01366
time 			 0.01337
like 			 0.0125
say 			 0.01133
doe 			 0.01104
lord 			 0.01104
make 			 0.01104
tis 			 0.01075
must 			 0.01046
done 			 0.01017
selfe 			 0.01017
ile 			 0.01017
feare 			 0.01017
let 			 0.01017
man 			 0.009881
wife 			 0.009881
night 			 0.009881
banquo 			 0.009881
well 			 0.00959
know 			 0.00959
one 			 0.0093
great 			 0.009009
see 			 0.009009
may 			 0.009009
exeunt 			 0.008718
speake 			 0.008428
sir 			 0.008428
lenox 			 0.008137
mine 			 0.007556
vp 			 0.007556
th 			 0.007556
mal 			 0.007265


In [15]:
bigram_measures = nltk.collocations.BigramAssocMeasures()

In [16]:
macbeth_finder = BigramCollocationFinder.from_words(macbeth_words_stopped)

In [17]:
macbeth_scored = macbeth_finder.score_ngrams(bigram_measures.raw_freq)

In [18]:
# Display the first 50 elements of macbeth_scored
macbeth_scored[:50]

[(('enter', 'macbeth'), 0.0015818091942659417),
 (('exeunt', 'scena'), 0.0014829461196243204),
 (('thane', 'cawdor'), 0.0012852199703410777),
 (('knock', 'knock'), 0.0009886307464162135),
 (('lord', 'macb'), 0.0008897676717745922),
 (('thou', 'art'), 0.0008897676717745922),
 (('good', 'lord'), 0.0007909045971329708),
 (('haue', 'done'), 0.0007909045971329708),
 (('macb', 'haue'), 0.0007909045971329708),
 (('enter', 'lady'), 0.0006920415224913495),
 (('let', 'vs'), 0.0006920415224913495),
 (('macbeth', 'macb'), 0.0005931784478497281),
 (('enter', 'malcolme'), 0.0004943153732081067),
 (('enter', 'three'), 0.0004943153732081067),
 (('euery', 'one'), 0.0004943153732081067),
 (('macb', 'ile'), 0.0004943153732081067),
 (('macb', 'thou'), 0.0004943153732081067),
 (('make', 'vs'), 0.0004943153732081067),
 (('mine', 'eyes'), 0.0004943153732081067),
 (('mine', 'owne'), 0.0004943153732081067),
 (('scena', 'secunda'), 0.0004943153732081067),
 (('three', 'witches'), 0.0004943153732081067),
 (('thy'

In [19]:
macbeth_pmi_finder = BigramCollocationFinder.from_words(macbeth_words_stopped)

In [20]:
macbeth_pmi_finder.apply_freq_filter(5)

In [21]:
macbeth_pmi_scored = macbeth_pmi_finder.score_ngrams(bigram_measures.pmi)

In [22]:
macbeth_pmi_scored[:50]

[(('three', 'witches'), 8.925697076191916),
 (('scena', 'secunda'), 8.844777080808349),
 (('knock', 'knock'), 8.62613679433301),
 (('thane', 'cawdor'), 7.968474805033251),
 (('exeunt', 'scena'), 7.844777080808349),
 (('mine', 'eyes'), 7.46626545755462),
 (('worthy', 'thane'), 6.982280604558284),
 (('mine', 'owne'), 6.838234234941577),
 (('euery', 'one'), 6.626136794333009),
 (('thou', 'art'), 5.861265203596917),
 (('enter', 'malcolme'), 5.585847073307292),
 (('enter', 'three'), 5.585847073307292),
 (('good', 'lord'), 5.441571341886851),
 (('let', 'vs'), 5.2009208910336255),
 (('enter', 'macbeth'), 5.0101623861741444),
 (('thy', 'selfe'), 4.689498855330438),
 (('make', 'vs'), 4.596849567364764),
 (('haue', 'done'), 4.2441883449377915),
 (('enter', 'lady'), 4.186751117897471),
 (('lord', 'macb'), 4.128174104483847),
 (('macb', 'ile'), 3.3988216944275145),
 (('would', 'haue'), 3.1408106050924847),
 (('macbeth', 'macb'), 2.836942806819401),
 (('macb', 'haue'), 2.2754392789222315),
 (('macb

# Other

$$\large E(X) = \mu = \sum p(xi)x_i$$



$p(2) \cdot 2$ = $\frac{1}{3} \cdot 2$ = $\frac{2}{3}$
$p(5) \cdot 5$ = $\frac{2}{3} \cdot 5$ = $\frac{10}{3}$

$$\large E((X-\mu)^2) = \sigma^2 = \sum p(xi)(x_i-\mu)^2$$

$$ \large N(x) = \dfrac{1}{\sigma \sqrt {2\pi }}e^{-\dfrac{(x-\mu)^2}{2\sigma^2}}$$


$$\Large z=\dfrac{x-\mu}{\sigma}$$

magine some test results follow a normal distribution with a mean score of 50 and a standard deviation of 10. One of the students scored a 70 on the test. Using this information and $z$-scores makes it easy to tell how she performed in terms of standard deviations from the mean. Converting a test score of 70 to a $z$-score, an $x$ of 70 would be, in this case:

$z = \dfrac{70 - 50}{10} = 2$

Measuring Skewness
For univariate data $Y1, Y2, ..., Y_n$ the formula for skewness is:

$$\dfrac{\dfrac{\displaystyle\sum^n{i=1}(Yi-Y)^3}{n}}{s^3}$$

where $Y$ is the mean, $s$ is the standard deviation, and $n$ is the number of data points. 

Measuring Kurtosis
For univariate data $Y1, Y2, \dots, Y_n$ the formula for kurtosis is:

$$\dfrac{\dfrac{\displaystyle\sum^n{i=1}(Yi-Y)^4}{n}}{s^4}$$

Mesokurtic ($\text{kurtosis} \approx 3 $)
A mesokurtic distribution has kurtosis statistics that lie close to the ones of a normal distribution. Mesokurtic distributions have a kurtosis of around 3. According to this definition, the standard normal distribution has a kurtosis of 3.

Platykurtic ($\text{kurtosis} < 3 $):
When a distribution is platykurtic, the distribution is shorter and tails are thinner than the normal distribution. The peak is lower and broader than Mesokurtic, which means that the tails are light and that there are fewer outliers than in a normal distribution.

Leptokurtic ($\text{kurtosis} > 3 $)
When you have a leptokurtic distribution, you have a distribution with longer and fatter tails. The peak is higher and sharper than the peak of a normal distribution, which means that data have heavy tails and that there are more outliers.

Outliers stretch your horizontal axis of the distribution, which means that the majority of the data appear in a narrower vertical range. This is why the leptokurtic distribution looks "skinny".

As stated above, we are often trying to infer population parameters from a sample. As such, we typically don't know the population variance or standard deviation. To start, it is thus natural to use the standard deviation of our sample as an estimate for the standard deviation of our population.

$S=\sqrt{\dfrac{1}{n-1}\sum\limits{i=1}^n (Xi-\bar{X})^2}$

So, when we go to find our confidence interval as before, our equation,

$\dfrac{\bar{X}-\mu}{\sigma/\sqrt{n}}\sim N(0,1)$

will become

$\dfrac{\bar{X}-\mu}{S/\sqrt{n}}$

(substituting S, the sample standard deviation, in for $\sigma$)

As a result, our question now becomes how is this quantity distributed?

$T=\dfrac{\bar{X}-\mu}{S/\sqrt{n}}$

While outside the scope of this discussion, it can be shown that this quantity can be modeled by a t-distribution. (Hence the use of the letter $T$).

With this, you can calculate confidence intervals for the population mean with your sample alone by using the equation:

$\bar{x}\pm t_{\alpha/2,n-1}\left(\dfrac{S}{\sqrt{n}}\right)$

To review some vocabulary and terms:

(1) $\bar{x}$ is a "point estimate" of

(2) $\bar{x}\pm t_{\alpha/2,n-1}\left(\dfrac{S}{\sqrt{n}}\right)$ is an "interval estimate" of

(3) $\dfrac{S}{\sqrt{n}}$ is the "standard error of the mean"

(4) $t_{\alpha/2,n-1}\left(\dfrac{S}{\sqrt{n}}\right)$ is the "margin of error"

$ \Large t = \frac{\bar{X1}-\bar{X2}}{\sqrt{\frac{{s1}^2}{N1} + \frac{{s2}^2}{N2}}} = \frac{\bar{X1}-\bar{X2}}{\sqrt{{se1}^2+{se2}^2}}$ where

$\bar{X_i}$ - mean of sample i
${s_i}^2$ - variance of sample i
$N_i$ - sample size of sample i

# Interview

In [19]:
n=[5,2,11,17,13]

for i in range(len(n)):
    for j in range(len(n)):
        if i!=j and i<j:
            if n[i]+n[j] == 18:
                print(i,j)

0 4


In [20]:
def sum_target(array, target):
    
    for i in range(len(array)):
        for j in range(len(array)):
            if i!=j and i<j:
                if array[i]+array[j]==target:
                    print(i,j)

In [21]:
sum_target([2,7,5,4,8,4,12,4],12)

1 2
3 4
4 5
4 7


# Other

### Average to 2 decimal places : `"{0:.2f}".format()`

In [23]:
student_marks={'Neha':[89,79,90], 'Sweta':[99,95,90]}
query_name = 'Sweta'

avg = sum(student_marks[query_name])/len(student_marks[query_name])
print("{0:.2f}".format(avg))

94.67


In [27]:
tuple(map(int, input().split()))

3 3 3


(3, 3, 3)

In [29]:
input().split()

3 3 3


['3', '3', '3']

In [30]:
input()

3 3 3


'3 3 3'

In [31]:
map(int,input().split())

3 3 3


In [32]:
tuple(map(int,input().split()))

3 3 3


(3, 3, 3)

In [33]:
import numpy as np

dim = tuple(map(int,input().split()))
print(np.zeros(dim))
print(np.ones(dim))

2 2
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [34]:
dim = tuple(map(int,input().split()))
print(np.zeros(dim,dtype=np.int))
print(np.ones(dim,dtype=np.int))

2 2
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [38]:
dim = tuple(map(int, input().split()))
print(np.identity(dim[0]))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:

np.set_printoptions(legacy='1.13')
dim = tuple(map(int, input().split()))
print(np.eye(dim[0]))



3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [42]:

np.set_printoptions(legacy='1.13')
dim = tuple(map(int, input().split()))
print(np.eye(dim))


3 4


TypeError: 'tuple' object cannot be interpreted as an integer

In [43]:

print(np.eye(*map(int, input().split())))

3 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


In [44]:

print(np.eye(map(int, input().split())))

3 4


TypeError: 'map' object cannot be interpreted as an integer

In [47]:
np.set_printoptions(legacy='1.13')
dim = (*map(int, input().split()))
print(np.eye(dim))

SyntaxError: can't use starred expression here (<ipython-input-47-eb0f3eef5bb6>, line 5)

In [55]:
n,m = map(int, input().split())

a = np.array(list(map(int, input().split())))
b = np.array(list(map(int, input().split())))

print(a+b)

1 4
2 5 9 7
 6 5 4 1
[ 8 10 13  8]


In [57]:
np.set_printoptions(legacy='1.13')

num = map(int, input().split())

a = np.array([input().split()],int)

b = np.array([input().split()],int)

print(np.add(a,b), np.subtract(a,b), np.multiply(a,b), np.floor_divide(a,b),np.mod(a,b), np.power(a,b), sep = '\n')

2 4
1 5 6 8
5 4 2 6
[[ 6  9  8 14]]
[[-4  1  4  2]]
[[ 5 20 12 48]]
[[0 1 3 1]]
[[1 1 0 2]]
[[     1    625     36 262144]]


### Palindromic triangle

In [60]:
for i in range(1,int(input())+1):
    print(int(((10**i-1)/9)**2))

5
1
121
12321
1234321
123454321


In [63]:
for i in range(1,int(input())+1):
    print(((10**i//9)**2))

5
1
121
12321
1234321
123454321


### Mod Divmod

**Divmod**: Returns quotient and remainder as a tuple.

In [65]:
a=int(input())
b=int(input())

print(a//b)
print(a%b)
print(divmod(a,b))

177
7
25
2
(25, 2)


### Alphabet Rangoli

In [67]:
import string
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [71]:
alpha = string.ascii_lowercase

In [70]:
n=int(input())

8


In [77]:
L=[]
for i in range(n):
    s = "-".join(alpha[i:n])
    L.append(s[::-1]+s[1:].center(4*n-3,"-"))
print('\n'.join(L[:0:-1]+L))

h-----------------------------
h-g---------------h-------------
h-g-f--------------g-h------------
h-g-f-e-------------f-g-h-----------
h-g-f-e-d------------e-f-g-h----------
h-g-f-e-d-c-----------d-e-f-g-h---------
h-g-f-e-d-c-b----------c-d-e-f-g-h--------
h-g-f-e-d-c-b-a---------b-c-d-e-f-g-h-------
h-g-f-e-d-c-b----------c-d-e-f-g-h--------
h-g-f-e-d-c-----------d-e-f-g-h---------
h-g-f-e-d------------e-f-g-h----------
h-g-f-e-------------f-g-h-----------
h-g-f--------------g-h------------
h-g---------------h-------------
h-----------------------------


In [76]:
L = []
for i in range(n):
    s = "-".join(alpha[i:n])
    L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
print('\n'.join(L[:0:-1]+L))

--------------h--------------
------------h-g-h------------
----------h-g-f-g-h----------
--------h-g-f-e-f-g-h--------
------h-g-f-e-d-e-f-g-h------
----h-g-f-e-d-c-d-e-f-g-h----
--h-g-f-e-d-c-b-c-d-e-f-g-h--
h-g-f-e-d-c-b-a-b-c-d-e-f-g-h
--h-g-f-e-d-c-b-c-d-e-f-g-h--
----h-g-f-e-d-c-d-e-f-g-h----
------h-g-f-e-d-e-f-g-h------
--------h-g-f-e-f-g-h--------
----------h-g-f-g-h----------
------------h-g-h------------
--------------h--------------


### Minion Game

In [78]:
vowel = 'AEIOU'

def minion_game(string,player1,player2):
    player1scr=0
    player2scr=0
    for i in range(len(string)):
        if string[i] in vowel:
            player1scr += (len(string)-i)
        else:
            player2scr += (len(string)-i)
    if player1scr>player2scr:
        print(player1,player1scr)
    elif player2scr>player1scr:
        print(player2,player2scr)
    else:
        print("Draw")
    

In [79]:
minion_game("BANANA","Sweta","Neha")

Neha 12


In [84]:
s = input()
k = int(input())

ti = []

n=int(len(s)/k)

m=0
while m<len(s):
    ti.append(s[m:m+n])
    m+=n

ti

DFDLLV
3


['DF', 'DL', 'LV']

In [85]:
s = input()
k = int(input())

ti = []

n=int(len(s)/k)

m=0
while m<len(s):
    ti.append(s[m:m+n])
    m+=n

ti

AAKDDNJKL
3


['AAK', 'DDN', 'JKL']

In [99]:
list(set(ti[i]) for i in range(len(ti)))

[{'A', 'K'}, {'D', 'N'}, {'J', 'K', 'L'}]

In [107]:
s = input()
k = int(input())

ti = []

n=int(len(s)/k)

m=0
while m<len(s):
    ti.append(s[m:m+n])
    m+=n

ui = list("".join(dict.fromkeys(ti[i])) for i in range(len(ti)))
ui

KKJNDHWWW
3


['KJ', 'NDH', 'W']

In [108]:
for i in range(0, len(s), k):
        uniq = ''
        for c in string[i : i+k]:
            if (c not in uniq):
                uniq+=c
        print(uniq)

TypeError: 'module' object is not subscriptable

### Set and Union, Intersection

**Only** works for **SET**

In [112]:
s=set("Rank")
s.union(set(("Hacker")))

{'H', 'R', 'a', 'c', 'e', 'k', 'n', 'r'}

In [113]:
s=set("Rank")
s.union("Hacker")

{'H', 'R', 'a', 'c', 'e', 'k', 'n', 'r'}

In [114]:
n = int(input())
eng_students = list(map(int, input().split()))
b = int(input())
french_students = list(map(int, input().split()))

es = set(eng_students)
print(es.union(french_students))

6
5 12 45 18 3 7
6
5 12 18 6 9 10
{18, 3, 5, 6, 7, 9, 10, 12, 45}


In [115]:
n = int(input())
eng_students = list(map(int, input().split()))
b = int(input())
french_students = list(map(int, input().split()))

es = set(eng_students)
print(len(es.union(french_students)))

6
5 12 45 18 3 7
6
5 12 18 6 9 10
9


In [116]:
n = int(input())
eng_students = list(map(int, input().split()))
b = int(input())
french_students = list(map(int, input().split()))

es = set(eng_students)
print(len(es.intersection(french_students)))

6
45 12 1 3 56 9
6
45 1 3 6 15 2
3


In [117]:
print(es.intersection(french_students))

{1, 3, 45}


## Python Problems

In [119]:
str.ascii_lowercase()

AttributeError: type object 'str' has no attribute 'ascii_lowercase'

### Check if palindrome

In [125]:
a="anna"
a[::-1]==a

True

In [126]:
"a" in "anna"

True

### Check if prime

In [3]:
10%7

3

In [11]:
number = int(input())

if number>1:
    for i in range(2,int(number/2)):
        if number%i == 0:
            print(f"{number} is not prime")
            break
    else:
        print(f"{number} is prime")
else:
    print(f"{number} is prime")

13
13 is prime


In [12]:
number = int(input())

if number>1:
    for i in range(2,int(number/2)):
        if number%i == 0:
            print(f"{number} is not prime")
            break
    else:
        print(f"{number} is prime")
else:
    print(f"{number} is prime")

1
1 is prime


### If monotonic

either always increasing or always decreasing

In [20]:
series = list(map(int, input().split()))

if all(series[i]>=series[i+1] for i in range(len(series)-1)) or all(series[i]<=series[i+1] for i in range(len(series)-1)):
    print("series is monotonic")
else:
    print("series is non-monotonic")

1 2 6 8 9 12
series is monotonic


In [21]:
series = list(map(int, input().split()))

if all(series[i]>=series[i+1] for i in range(len(series)-1)) or all(series[i]<=series[i+1] for i in range(len(series)-1)):
    print("series is monotonic")
else:
    print("series is non-monotonic")

1 5 6 2 8 4 6 23
series is non-monotonic


### Duplicates

In [23]:
def del_duplicates(series):
    unique=[]
    for i in range(len(series)):
        if series[i] not in unique:
            unique.append(series[i])
    return unique

In [24]:
del_duplicates([1,2,3,6,6,5,5,8,8,9,4,4,6])

[1, 2, 3, 6, 5, 8, 9, 4]

In [28]:
def find_duplicates(series):
    duplicates = []
    for i in range(len(series)):
        for j in range(len(series)):
            if i!=j:
                if series[i]==series[j] and series[j] not in duplicates:
                    duplicates.append(series[j])
    return duplicates

In [29]:
find_duplicates([1,2,3,6,6,5,5,8,8,9,4,4,6,5,6,7])

[6, 5, 8, 4]

### recurring numbers

In [37]:
# 1st non-recurring number
s=[1,1,1,1,2,3,6,4]
for i in range(len(s)-1):
    if s[i]!=s[i+1]:
        print(s[i+1])
        break

2


In [67]:
# most recurring nummber
s=[1,1,6,3,6,5,8,9,5,5,2,36,3,2,1,2]
k=max(s,key=s.count)
print(k)

1


In [43]:
s.sort()
s

[1, 1, 1, 2, 2, 2, 3, 3, 5, 5, 5, 6, 6, 8, 9, 36]

In [44]:
s.sort(reverse=True)
s

[36, 9, 8, 6, 6, 5, 5, 5, 3, 3, 2, 2, 2, 1, 1, 1]

In [45]:
list(set(s))

[1, 2, 3, 36, 5, 6, 8, 9]

In [56]:
# counter - or, refer to flatiorn material
unique = list(set(s))
number=dict.fromkeys(unique,0)
    
for i in range(len(s)):
    if s[i] in list(set(s)):
        number[s[i]]+=1

In [57]:
number

{1: 3, 2: 3, 3: 2, 36: 1, 5: 3, 6: 2, 8: 1, 9: 1}

In [70]:
for i in s:
    print(f'{i}: {s.count(i)}')

1: 3
1: 3
6: 2
3: 2
6: 2
5: 3
8: 1
9: 1
5: 3
5: 3
2: 3
36: 1
3: 2
2: 3
1: 3
2: 3


### GCF,lcm

In [59]:
a = 15
b = 20
 
while b:
    a,b=b,a%b
 
print(a)

5


In [60]:
#Lowest common Factor
 
a = 15
b = 20
c = a
d = b
 
while b:
    a,b=b,a%b
 
lcm = int( (c*d) * 1.0 / a)
 
print(lcm)

60


### Other

In [64]:
c = ['a','b','c','d','e']
 
strs = (''.join(c))
strs

'abcde'

In [63]:
#Find common words from two sentences
 
a = 'Hi I am Pawan. I am here only'
b = 'here only'
d = {}
 
for w1 in a.split():
    for w2 in b.split():
        if w1 == w2:
            d[w1] =  d.get(w1,0) + 1
 
print(d)

{'here': 1, 'only': 1}


In [65]:
a = 'Hi I am Pawan. I am here only'
b = 'here only'
d = {}

for w1 in a.split():
    for w2 in b.split():
        if w1!=w2:
            d[w1]=d.get(w1,0)+1

print(d)

{'Hi': 2, 'I': 4, 'am': 4, 'Pawan.': 2, 'here': 1, 'only': 1}


In [66]:
a = 'Hi I am Pawan here only'
b = 'here only'
d = {}
 
for w in a.split():
    d[w] = d.get(w,0) + 1
     
for w in b.split():
    d[w] = d.get(w,0) + 1
 
print("The original string is - ",d)
 
print("\n")
 
uncon = [w for w in d if d[w] == 1]
 
print("The uncommon words from two input strings is - " , uncon)

The original string is -  {'Hi': 1, 'I': 1, 'am': 1, 'Pawan': 1, 'here': 2, 'only': 2}


The uncommon words from two input strings is -  ['Hi', 'I', 'am', 'Pawan']


### Fibonacci (0,1,1,2,3,5,8)

In [75]:
n = int(input())
f =[0,1]
for i in range(n):
    f.append(f[i]+f[i+1])
f

6


[0, 1, 1, 2, 3, 5, 8, 13]